### PR TITLE
Adding CustomItem name and special lore for SpoutItemStack ItemMeta

### PR DESCRIPTION
**Pull request by skyforce77**
This can be usefull for people who don't have spoutcraft  and have a lot of customitems on inventory.

Signed-off-by: skyforce77 arnaud.bruyer@gmail.com

### CODE REVIEW

**Comment by skyforce77** [comment]
Sorry for the number of commits, searched the better thing to do that ^^'

**Comment by lukespragg** [comment]
You'd need to squash the commits, and actually sign off on the commits, not the PR comment. ;)

**Comment by skyforce77** [comment]
I don't know how to make this with github. I haven't used it before.

**Comment by ZNickq** [comment]
in command line:
git rebase -i HEAD~5

a new window will appear with all the 5 commits, change the last 4 ones from "pick" to "squash", save and quit (usually esc+ :qw)
another window will appear, remove all text from it other than what you want the commit message to be, then save and quit again, and finally force push to the repo using git push -u -f origin master

**Comment by skyforce77** [comment]
Squashed! but i don't know how to sign off the commits (i use github.exe, not git)

**Comment by lukespragg** [comment]
It isn't squashed yet. Notice the 5 commits still showing? ;)

Your formatting also doesn't match our conventions. If we do use this, we'll likely just have to manually merge it, so closing for now.

**Pull request closed without merging**
