### PR TITLE
Replaced some spaces with tabs

### PR DESCRIPTION
**Pull request by windy1**
Signed-off-by: WalkerCrouse (Windwaker) wjcrouse913@aim.com

### CODE REVIEW

**Comment by zhuowei** [comment]
I thought the Spout coding style required tabs?

Edit: Look at readme.md: "Use tabs, no spaces."

**Comment by windy1** [comment]
Yes.. which is why I "replaced the spaces with tabs" :p

**Comment by zhuowei** [comment]
I can't read, sorry.

**Comment by windy1** [comment]
lol no worries

**Comment by Top-Cat** [comment]
tbf the notification I got said "Replaced some tabs with spaces" as well :/
At least the pull is right

**Comment by windy1** [comment]
That's weird, I accidentally had that as the original title, but edited it within 20 seconds after posting it.

**Pull request merged**
