### PR TITLE
Update to new event system

### PR DESCRIPTION
**Pull request by windy1**
Title says it all ^.^

Signed-off-by: WalkerCrouse (Windwaker) wjcrouse913@aim.com

### CODE REVIEW

**Comment by zhuowei** [comment]
Awesome!

**Comment by md-5** [comment]
lol wat I did this in pr #8 and this was merged first :/

**Comment by windy1** [comment]
Yeah, I noticed after it was merged, sorry :p

**Comment by Top-Cat** [comment]
I also was a silly goose, they're both merged tho

And I did a manual merge for you @md-5

**Pull request merged**
