### PR TITLE
Armor

### PR DESCRIPTION
**Pull request by trentonfaris**
Just realized that the way I edited the files caused it show up as though I had deleted and re-pasted the whole file. Sorry about that. This is my first time using Github...

Anyways, I believe I've added custom armor correctly.

Also, I have NO idea why it included this other guy's stuff.

### CODE REVIEW

**Comment by lukespragg** [comment]
Yeah, this will need major cleanup. ;)
You also used the newprecache branch from the looks of it, instead of the master.

**Comment by trentonfaris** [comment]
Oh ok. Ya I wasn't sure what happened. For the editing, I had both the local file that I created and the temporary Github file side by side in Eclipse. I changed things one line at a time, but it looks like for some reason it changed the whole file. Sorry about that.

MC

**Comment by trentonfaris** [comment]
Do I need to redo it or is there a simpler way of cleaning that up?

MC

**Comment by lukespragg** [comment]
Sorry for the late reply. This would need to be updated to the latest on master, your commits squashed together, and then committed to a branch just for it so that the other commits that aren't yours don't get pulled into this PR.

**Comment by lukespragg** [comment]
Closing this for now, but I'll see if someone can take a look at it and manually add it when able.

**Pull request closed without merging**
