### PR TITLE
Fixed removeWidgets removing hardcoded widgets!

### PR DESCRIPTION
**Pull request by ZNickq**
It now catches the error properly ;)

### CODE REVIEW

**Comment by Zidane** [comment]
Shouldn't you do something more proper with the error? Such as implementing a supported operation?

**Comment by ZNickq** [comment]
Nah, there's really nothing better to do, since no plugin other than SpoutPlugin can create those widgets :P

**Comment by Zidane** [comment]
Also @Znickq...it isn't signed off.

**Comment by ZNickq** [comment]
This is SpoutPlugin...afaik it doesn't require signing off...does it?
LE: Nope, it's not using the SpoutDev license...

**Comment by Afforess** [comment]
Just no.

**Pull request closed without merging**
