### PR TITLE
Finalized block rotation stuff.

### PR DESCRIPTION
**Pull request by IceReaper**
- Implemented full rotation api. Blocks can now be rotated on each axis instead of only one.
- Implemented collision model change for upside-down blocks (slabs, stairs, ...)
- Also this would technically allow blocks to be rotated on the side - just needs to be used.

Signed-off-by: Andre Mohren andre@eiveo.net

### CODE REVIEW

**Comment by ZNickq** [comment]
Looks awesome, can you rebase though? (git pull --rebase _spoutRepo_ master, then git push _yourRepo_ master)

**Comment by Raphfrk** [comment]
This works by using the falling sand system?

**Comment by IceReaper** [comment]
Well, basicaly SpoutPlugin allows 256 shapes per block, it already used the following:
0 - normal block
1 - 3 normal block rotation

so i added
4-7 upside-down block rotation (stairs, slabs..)

and when thinking about it, i also added all possible 90 degreee rotations (6x4) so
8-23 all other rotation posibilities.

rotation was already implemented, now rotates also the base-block - usefull for stair-collisions.
4-7 now also got their collision - so upside-down stairs have also matched collision.
placement for upside down is by looking over 45 degrees above when placing.

the other rotation shapes are currently not placeable - but can be used by plugins.
i can ofcourse remove them from the commit if you want - so other plugins must implement them by themself.

However the other thing i added is a correction .rotate() method. it can rotate around every axis now - which in my eyes is usefull for SpoutPlugin.

What do you mean by "falling sand system" ?

**Comment by Raphfrk** [comment]
Ahh ok.

By falling sand, I mean the fact that falling sand blocks are entities.  This means that they don't have to be aligned with other blocks.  I was just wondering if that is what you were using for rotation.  I don't even know if falling sand can be rotated.

Anyway, with the latest protocol, non-sand can also "fall".

**Comment by Zidane** [comment]
@Raphfrk 

Funny thing is, the client also assumes that the falling block will die shortly after spawn (from dieing by impact or after 4-5 seconds) so it removes its hit box after physics occurs from the client-side AABB pool (eventhough the entity can still be there :p)

**Comment by Raphfrk** [comment]
@Zidane

Interesting, so if you click on a falling sand block, it sends an entity interact packet to the server?

Does the entity still show up on the client though?  In theory, you could keep resending them but that wouldn't give very smooth movement.  

Can falling sand blocks be rotated?  Anyway, this is taking this off-topic.

**Comment by Zidane** [comment]
@Raphfrk 

Gave us a thread: http://forums.spout.org/threads/the-falling-block-and-the-official-client.5436/

**Comment by Dockter** [comment]
Cant wait for this to get pulled.

**Comment by ZNickq** [comment]
I will talk to IceReaper today about rebasing this, it should be pulled soon :)

**Pull request merged**
