### PR TITLE
A few things

### PR DESCRIPTION
**Pull request by md-5**
Make reloading work a bit better
Use the new event system
Clean up one or two code quirks
Squash a warning or two
Remove some redundant casts

### CODE REVIEW

**Comment by Top-Cat** [comment]
This pull request cannot be automatically merged...

**Comment by md-5** [comment]
Thats because someone changed one of the files in it recently
I can do a rebase if you want

**Comment by Top-Cat** [comment]
That was what I was implying

**Comment by md-5** [comment]
Jenkins will hate you unless you merge: https://github.com/SpoutDev/SpoutPluginAPI/pull/5

**Pull request merged**
