### PR TITLE
Make getClass use instanceof instead

### PR DESCRIPTION
**Pull request by md-5**
Allows for people like me to extend the SNSH

### CODE REVIEW

**Comment by Raphfrk** [comment]
Hmm, that doesn't sounds very stable.  You would have use replacing NSH and then having that replaced?

**Comment by md-5** [comment]
It's exactly what you are doing already! I am replacing the current NSH with mine. The current NHS in some cases is Spout's, but as my NSH only overrides methods yours doesn't, I just take my normal NSH and instead of Extending NSH I extend SNSH.

**Comment by Raphfrk** [comment]
I mean doing it twice doubles the risk :p.  I can only imagine how handling reloads would work (not that we do).

**Comment by md-5** [comment]
I reload and it works fine :) I softdepend on Spout so I will always replace yours, not the other way around.

**Comment by Raphfrk** [comment]
Hmm, Spout pretty much explodes on reload, IIRC

**Comment by md-5** [comment]
Hmm It gives a huge error, but I just ignore it and it works fine

**Pull request merged**
