### PR TITLE
Added CustomArmor.

### PR DESCRIPTION
**Pull request by Wolftein**
Signed-off-by: Wolftein agustin.l.alvarez@hotmail.com

### CODE REVIEW

**Comment by lukespragg** [comment]
Such a descriptive PR title. :P

**Comment by Spouty** [comment]
**[AUTO-GENERATED COMMENT]**

This pull request has only **_1 commit**_ and is **_signed off**_.
Thanks for following the [pull request guidelines](http://spout.in/prguide) and for your contribution!
A [team member](http://spout.org/team) will review this pull request when time allows.

**Comment by igniansoft** [comment]
Spouty fail^^ :D

Yay, custom armor!!!

**Comment by stephenwilliams** [comment]
@igniansoft ... how did Spouty fail?

**Comment by skyforce77** [comment]
Good work Wolftein ;)

**Comment by ZNickq** [comment]
Reopen the PR when it's finished completely, we can't pull unfinished stuff :P

**Comment by Wolftein** [comment]
@ZNickq: SpoutPlugin and SpoutcraftAPI is already finished.

**Comment by igniansoft** [comment]
@alta189 there were, multiple commits -.-

**Comment by Pamelloes** [comment]
I've talked about doing this in the past and the way shown here is probably not the best approach. For one, it is probably best to make sure that all custom materials use **flint**. Using another material will have unintended side effects and will probably prevent the PR from being accepted. However, when using flint, all you need to do is copy the tool code with just a few changes client side and server side to allow it to be set as armor and register for damage events to modify the results appropriately.

**Comment by Wolftein** [comment]
Is working great! @Pamelloes

**Comment by stephenwilliams** [comment]
@igniansoft when Spouty recieved the notice, it was only one commit

**Comment by igniansoft** [comment]
@alta189 I know,hence the laughing face :)

**Pull request closed without merging**
